### ISSUE TITLE
Screen Blur Removal and Buffout 4 CTD on launch

### ISSUE THREAD

**Issue by blazeblue32** [interworlder/FROST-Fast#1]
Hi, I recently install your mod list, and it seemed to run fine until I tried to install a mod that relied on Buffout 4. That mod isn't important, I since uninstalled it while trouble shooting, but it made me realize that I hadn't put the F4SE folder from the Game Folder Files into the Data folder, meaning that Buffout 4 hadn't been running. The list seemed to work fine until I fixed this oversight.
Took a while, but after reinstalling the list, reinstalling fallout, reinstalling the prerequisites with no success, I started going through the mod list, disabling all mods and working my way through them. The list runs fine if I have either mod active, but not both at the same time. 

Is this a me issue, or can anyone replicate it?

**Comment by blazeblue32** [comment]
Sweet, thanks for sorting it out so quick. I'll definitively keep an eye out for anything else.

**Comment by interworlder** [comment]
Oops. That should now be fixed as well. Just released v1.4.0!
