### ISSUE TITLE
Easier Setup Mods

### ISSUE THREAD

**Issue by shallow-beach** [interworlder/FROST-Fast#4]
Hello, fantastic package!

Two lightweight mods I think are essential with this:

https://www.nexusmods.com/fallout4/mods/26163
Unlimited Survival Mode 
 - Thus initial MCM setup save can be made. Important for repeated playthroughs. 

https://www.nexusmods.com/fallout4/mods/56311
NPCs Travel MCM Settings
 - I don't spawn with the holotape to adjust necessary mod settings, finding anything in this world is scary so this is a must.

**Comment by interworlder** [comment]
Thank you for the suggestions, I have added these mods for the next release!
