### ISSUE TITLE
Some recommeneded mods from a modlist 2022

### ISSUE THREAD

**Issue by outcrane** [interworlder/FROST-Fast#5]
I love the idea of a fully fleshed out wabbajack FROST mod list. It seems you've already got it nearly there. I saw some interesting additions in this other manual modlist i think you should check out. [Here](https://docs.google.com/document/d/1S9OpgbcNGCplKM_BrnksRCu8Y3vqYMkHkY4rXseZ0zE/edit?usp=drivesdk) 
 
https://docs.google.com/document/d/1S9OpgbcNGCplKM_BrnksRCu8Y3vqYMkHkY4rXseZ0zE/edit?usp=drivesdk

**Comment by interworlder** [comment]
Thank you, I didn't realize that recommendation list got updated! I've added some of the new mods, and they will go out with the next release.
