### ISSUE TITLE
surface radiation only working half of the time

### ISSUE THREAD

**Issue by jjYBdx4IL** [interworlder/FROST-Fast#6]
I'm on modlist 1.4.1 and playing a ghoul.

What could be the cause of that issue?

And what about the 4K textures in 1.5.0? Will 1.5.0 kill my performance? Can I disable them?

**Comment by interworlder** [comment]
Hello! You should be immune to most sources of radiation when playing as a ghoul. I believe very strong sources of radiation will still affect you, but normal surface radiation will not.

Yes, all of the 4K textures can be disabled. In testing, I saw a maximum utilization of ~7GB VRAM, which should be OK for GPUs with at least 8GB VRAM. I believe a bigger performance hit will come from Wasteland Illumination Shadow Version, and that can be disabled too.

With that said, I will be removing most of the 4K textures in the next release. I believe users should be able to choose between high- and low-end requirements, and it's better to reduce the download size anyway. The snowy winter textures will stay, but the rest will probably go into an "Optional" section of the Readme.

Thanks for the feedback!

**Comment by jjYBdx4IL** [comment]
yes, the ghoul is resistant, however I'd like to use the ghoulish perk to restore hp, that's why it's so noticeable xD

Also, this whole business of filling water bottles is insane. if you do that at a pump, I had to set "bAlwaysActrive=1" so I could watch YT vids while the character was doing it.....

Regarding VRAM, v1.4.1 works perfectly on 3GB of VRAM installed into my GTX 1060 at FullHD@60.

**Comment by interworlder** [comment]
Oh, I see. The Ghoulification perk negates rad damage, so then the Ghoulish perk can't use rad damage for health restoration. I don't know if that is intentional or not, but I'd recommend sending this feedback to [FROST Plus](https://www.nexusmods.com/fallout4/mods/48847).

**Comment by jjYBdx4IL** [comment]
no, it works. it's just that surface radiation sometimes doesn't exist. not sure why. Maybe it's because of the weather? During rad storms, the surface radiation isn't there either, just the radiation peaks from the weather. So maybe it's a specific weather situation that isn't accounted for? Or bugged because of mod conflicts?

**Comment by interworlder** [comment]
Does the surface radiation get applied when you are playing as a human?

**Comment by jjYBdx4IL** [comment]
think so. except for rad storms. there I get the rad spilkes, but not the constant surface radiation. when playing as a ghoul there also seems to be no radiation at all at times, so maybe it's not related to surface radiation in particular. well, doesn't matter really, was just wondering whether there are known issues in that regard.

**Comment by interworlder** [comment]
Understood, thank you for the details. I don't believe this is a bug or an error in the modlist, but it might be an unexpected interaction. The Ghoulification perk is removing rad damage at all times, so rad damage can never accumulate on the player, and therefore there is no rad damage for Ghoulish to convert into healing.

It sounds like surface radiation is working normally, but the problem is that you cannot see it. +5 rad/s from surface radiation is covered up by -35 rad/s from Ghoulification (constant spell effect on the player).

This feedback should go to the FROST Plus developer, as it may or may not be an intended effect of the Ghoulification perk.

**Comment by jjYBdx4IL** [comment]
well, ok, but it's definitely a bug because it's inconsistent and sometimes works and sometimes doesn't.
