### ISSUE TITLE
Stock Game Folder

### ISSUE THREAD

**Issue by BFJ148** [interworlder/FROST-Fast#7]
Any thoughts on moving to a SGF like many other WJ lists out there?

**Comment by interworlder** [comment]
Thanks for letting me know! I didn't even realize this was possible with Wabbajack, but I can definitely see the advantages. I will work on making it happen for the next release.

[for my reference](https://github.com/wabbajack-tools/wabbajack/wiki/Keeping-The-Game-Folder-Clean-(via-local-game-installs))

**Comment by BFJ148** [comment]
No problem and right on bud. You gotta get this up on the wabbajack ui only reason I know of it is from randomly hitting r/fodust

**Comment by interworlder** [comment]
I took a closer look at the documentation for setting up a Stock Game Folder. Unfortunately the legality of redistributing the necessary files through a .wabbajack file seems a little questionable, so I must close this ticket as incomplete. :(

**Comment by jjYBdx4IL** [comment]
how so?

**Comment by interworlder** [comment]
The steps for setting up a Stock Game Folder involve packaging Bethesda assets into the .wabbajack file itself instead grabbing them from another source (like the enduser’s installation). I don’t think Bethesda would prosecute me, but I also don’t feel comfortable redistributing files which I don’t have explicit rights to.
