### ISSUE TITLE
quick looting hangs the game

### ISSUE THREAD

**Issue by jjYBdx4IL** [interworlder/FROST-Fast#8]
seems reproducible to some extent. since v1.5.1 (.0?). what mod could cause that?

**Comment by jjYBdx4IL** [comment]
culprit is: https://www.nexusmods.com/fallout4/mods/18077?tab=bugs
see also: https://steamcommunity.com/app/377160/discussions/0/1327844097109060327/?ctp=2

**Comment by interworlder** [comment]
Thanks for the report! This will get removed in the next version.
